@extends('layouts.simple_pages_header')
@section('content')


<main id="content" role="main">
    <!-- Hero -->
    <div class="bg-img-start" style="background-image: url({{ asset('svg/components/card-11.svg') }} );">
      <div class="container content-space-t-3 content-space-t-lg-5 content-space-b-2">
        <div class="w-md-75 w-lg-50 text-center mx-md-auto">
          <h1 style="font-family:Work Sans; font-weight:700;">Terms and Conditions <Br/></h1>
          <p><small style="font-weight:500;color:#000;">Here are the terms & conditions that governs our crypto staking project. <i class="text-info text-xs">Last Updated 04/06/2022</i></small></p>
        </div>
      </div>
    </div>
  
   <div class="container content-space-t-3 content-space-t-lg-4 content-space-b-2" style="margin-top:-140px;">
      <div class="w-lg-65 mx-lg-auto">
  <p style="font-family:'Spartan','Work Sans','Brandon Grotesque'; font-size:14px;font-weight:500;">
  <b>TERMS OF SERVICE</b><br/>
  
BalmFlow, LLC (“BalmFlow”, the “Company,” “Us,” “Our” or “We”), by and through https://balmflow.com (the “Site”), operates, hosts and monitors and trade stable cryptocurrencies - USDT & by extension USDC against other currencies - Euro, and the Great Britain Pounds (as defined below, the “Services”). 
BalmFlow provides Services pursuant to, and in accordance with, the following terms and conditions (this “Agreement” or “Terms of Use”). The Foundation Project ("Help the Poor Project - A health initiative to help those hospitalized without means to afford health bills")
Accessing, browsing or viewing the Site, including, but not limited to, registering for an account, submitting any information to Us, or utilizing any of the Services as provided and offered by BalmFlow, you hereby consent and agree to be bound by these Terms of Use, as contained herein.
You (“Client”) agree to be bound by these Terms of Use and all other operating rules, policies and procedures that may be published by Us from time to time on the Site, each of which is incorporated by reference and each of which may be updated by Us from time to time without notice to you. Your use of the Site is governed by the version of these Terms of Use in effect on the date of use.

<BR/>
<BR/>
<B>1. Definitions</B><bR/>
<b>“Blockchain”</b> means a digital ledger in which transactions made with a Cryptocurrency are recorded chronologically.<Br/>
<b>“Cryptocurrency”</b> means a digital currency, operating independently of a central bank, in which encryption techniques are used to regulate the generation of units of currency and verify the transfer of funds.<br/>
<b>“Client Data”</b> means all data, files and information that Client provides to BalmFlow in the course of using the Services.<br/>
<b>“Client Funds”</b> means the Cryptocurrency funds staked or donated by Client to BalmFlow either for charity purposes or contributory purpose upon which a daily rebate is applicable as means of giving back to our contributors whom we see as stakeholders in the interest of our "Help the poor Project".<br/>
<b>“Net Revenue”</b> means Staking Rewards minus any transactional charges assessed, if applicable. <br/>
<b>“Pooled Staking Service”</b> means the BalmFlow Service that runs Trading activities on the pooled funds and allows investors to Stake their Cryptocurrency holdings in exchange for a percentage of the Net Revenue generated from Staking. <Br/>
<b>“Slashing Penalty”</b> means any penalty assessed by the Cryptocurrency for unavailability or slow, incorrect or malicious performance.<br/>
<b>“Staking”</b> or “to Stake” means committing Cryptocurrency as a monetary fund to be traded with on designated financial markets.<Br/>
<b>“Staking Rewards”</b> means all Cryptocurrency generated by trading activities including, but not limited to, daily rebates, affiliate rewards, transaction fees and any other direct payments as a result of the trading activities. <Br/>
<b>“Supported Protocol”</b> means a Cryptocurrency for which BalmFlow operates Staking Nodes. <br/>
<b>“Revenue Share Payments”</b> means the percentage of Net Revenue paid to Client as set forth in Section 2(c). <br/>
<b>“Unbonding Period”</b> means the Cryptocurrency imposed waiting period, during which the Client Funds and End Users Funds may not be withdrawn or sold.

<!--the above section has been read and proof-read-->

<BR/>
<BR/>
<B>2. BalmFlow RESPONSIBILITIES</B><BR/>

a. Trading Services. During the Term, BalmFlow will provide the Trading Services on behalf of The Foudnation Project and by extension the Client in accordance with the service level terms set forth below.<br/>
b. Server Procurement, Setup, Broker & Market selection & Maintenance. BalmFlow will determine, in its sole discretion, the network and server requirements to reliably use in our trading activities. 
BalmFlow is responsible for all costs associated with procuring, installing servers, expert algorithms and running trading activities.<br/>
c. Revenue Share Payments: BalmFlow will pay Client a percentage of Net Revenue directly attributable to Client Funds. 
Pooled Staking Services will pay a percentage of Net Revenue that will vary by Cryptocurrency, and will be posted on the client's account. All Revenue Share Payments will be made in the same Cryptocurrency in which the Client Funds or End Users Funds are denominated, as applicable.<br/>
d. Reporting: BalmFlow will provide regular reports through our dashboard detailing the performance of the Services to Client. Such reports will provide mutually agreeable details to enable the accurate calculation of Net Revenue.

<BR/><B>3. CLIENT RESPONSIBILITIES</B><BR/>
a. Stake Delegation. Client will have the sole right to determine the amount of Client Funds and End Users Funds which will be BalmFlow pursuant to this Agreement.
b. Withdrawals. Client acknowledges and agrees that Client Funds and End Users Funds which have been BalmFlow's pursuant hereto may not be withdrawn prior to the conclusion of the Unbonding Period which is 12 months from the time of staking. For clarity purposes, withdrawals are only permitted on rewards tagged as "withdrawable balance" on the client's dashboard.
c. Taxes: Client shall be responsible for payment of all applicable taxes to their respective government, if any, to which the Revenue Share Payments might be subject and any and all other taxes which may apply to Client; 
BalmFlow makes no representations in this regard. Client agrees to indemnify and hold BalmFlow harmless against any taxes, including penalties, duties and interest levied by any government on the Revenue Share Payments.

<BR/><B>4. LICENSE GRANT; RESTRICTIONS</B><BR/>
a. Proprietary Rights. Client acknowledges and agrees that this license conveys no title or ownership rights to the BalmFlow Services. 
Client does not acquire any rights in the Services, express or implied, other than those expressly granted in this Agreement and all rights not expressly granted to Client are reserved by BalmFlow. <br/>
BalmFlow retains all right, title and interest in and to the BalmFlow Services, including without limitation, all unpatented inventions, patent applications, patents, design rights, copyrights, trademarks, service marks, trade names, know-how and other trade secret rights, and all other intellectual property rights, derivatives or improvements thereof.<br/>
b. Restrictions. Client will not, and will not permit any other third party to modify, reproduce, copy, reverse engineer, decompile, reverse assemble or otherwise attempt to discover the source code or algorithms for the BalmFlow Services, or access the Services in order to build a similar or competitive product or service. 
Client will not, and will not permit any of its End Users or other third party to use any device, software or routine to interfere with the proper function of the Services. 
The BalmFlow Services may not be used in any jurisdiction for unlawful, obscene, offensive or fraudulent content or activity, such as advocating or causing harm, interfering with or violating the integrity or security of a network or system, evading filters, sending unsolicited, abusive, or deceptive messages, viruses or harmful code, or violating third party rights. If there is a complaint or notice of violation, use may be suspended until resolved, and terminated if not resolved promptly.

<BR/><B>5. TERM & TERMINATION</B><BR/>
a. Term. Agreement will commence upon the Effective Date and, unless earlier terminated as set forth below, continue for a period of twelve months (the “Initial Term”). 
Thereafter, the Agreement will automatically renew for successive twelve-month periods (each, a “Renewal Term”), 
unless either party provides written notice to the other of its desire to terminate no later than sixty (60) days prior to the expiration of the then-current term. 
As used herein, “Term” means the Initial Term plus any Renewal Term(s).<Br/>
b. Termination. Either party may terminate this Agreement if the other party fails to cure any material breach of this Agreement within thirty (30) days after receipt of written notice describing the breach in reasonable detail. 
In addition, BalmFlow may terminate this Agreement on seven (7) days written notice for any reason or no reason whatsoever.<br/>
c. Effect of Termination. 
Upon termination or expiration of this Agreement: (i) all rights and obligations of both parties, including all licenses granted hereunder, shall immediately terminate, (ii) ii) each party will destroy all Confidential Information and other materials of the other party in its possession and (iii) Sections 4(b), 5(c), 6, 7(c), 8, 9 and 14, together with any payment obligations existing as of the effective date of termination, will survive.<br/>
d. Every staked funds shall have a period of daily reward/rebate for a period of 12 months or Two-hundred percent of the initial staked funds which may elapsed beyond 12 months from the time of staking
e. Clients shall not have access to the staked funds but will only get Two-hundred percent of whatever has been staked

<BR/><B>6. CONFIDENTIALITY</B><BR/>
The parties acknowledge that the terms of this Agreement will be confidential. 
The parties further acknowledge that, in the course of performing duties under this Agreement, 
each party may obtain from the other party data or information of a confidential or proprietary nature, including know-how and trade secrets, relating to the business, the affairs, 
the development projects, or current or future products or services of such party (“Confidential Information”). <br/>
Data or information will be considered Confidential Information if: <br/>
(a) a party has marked it as such; <Br/>(b) a party, orally or in writing, has advised the other party of its confidential or proprietary nature, or <Br/>
(c) due to its character and nature, a reasonable person under like circumstances would treat it as confidential. <Br/>
Neither party will either: <Br/>
(i) publish, disclose or otherwise divulge any of the other party’s Confidential Information to any person, except its officers, 
employees or agents with a need to know who are under a contractual or professional duty to maintain the confidentiality of such information consistent with the obligations imposed hereunder; 
or<Br/>
(ii) permit its officers, employees or agents to divulge any of the other party’s Confidential Information without the express prior written consent of the other party. 
The receiving party will protect the disclosing party’s Confidential Information with the same degree of care that the receiving party protects its own information of a similar nature, 
but in no event less than reasonable care. 
Neither party will use the other party’s Confidential Information except in the course of performing its duties under this Agreement. 
The foregoing obligations will not apply to any Confidential Information that <Br/>(1) is already known to the receiving party; <Br/>
(2) is or becomes publicly known through no wrongful act of the receiving party; <Br/>
(3) is independently developed by the receiving party without benefit of the disclosing party’s Confidential Information; <Br/>
(4) is received from a third party without similar restriction and without breach of any obligation of confidentiality; or <Br/>
(5) is required or reasonably necessary to be disclosed to comply with laws, statutes, regulations, orders, and other governmental rules. Additionally, 
neither party will be prohibited from disclosing the terms and conditions of this Agreement to financial institutions when required to obtain financing or 
to a third party involved with a potential merger or acquisition (either as target or acquirer). 
The obligations of confidentiality described above will expire one year after the expiration or termination of this Agreement.

<BR/><B>7. REPRESENTATIONS & WARRANTIES</B><BR/>
a. Representations and Warranties by BalmFlow. BalmFlow represents and warrants to Client that: <br/>
(i) it has the power and authority to enter into this Agreement, <br/>
(ii) entering into this Agreement will not be a breach or violation of any other contract or agreement to which BalmFlow is bound, <br/>
(iii) it provides the Services using commercially reasonable care and skill in accordance with the service levels outlined<br/>
b. Representations and Warranties by Client. Client represents and warrants to BalmFlow that: 
(i) it has the power and authority to enter into this Agreement, and (ii) entering into this Agreement will not be a breach or violation of any other contract or agreement to which Client is bound.
c. Disclaimer. EXCEPT FOR THE EXPRESS WARRANTIES STATED IN THIS SECTION 7, NEITHER PARTY MAKES, AND EACH PARTY EXPRESSLY DISCLAIMS, ALL WARRANTIES, EXPRESS, IMPLIED, STATUTORY OR OTHERWISE, WITH RESPECT TO THE SERVICES AND THE SUBJECT MATTER OF THIS AGREEMENT, INCLUDING WITHOUT LIMITATION IMPLIED WARRANTIES OF ACCESS, MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND IMPLIED WARRANTIES ARISING FROM COURSE OF DEALING OR COURSE OF PERFORMANCE. EXCEPT AS STATED IN THIS SECTION 7(a), THE SERVICES ARE PROVIDED TO CLIENT ON AN “AS IS” AND “AS AVAILABLE” BASIS, AND ARE FOR COMMERCIAL USE ONLY. Client understands that while BalmFlow employs measures to ensure that the Services are accessible 24 hours a day/7 days a week, BalmFlow cannot guarantee the uninterrupted or error-free operation performance of the Services or that BalmFlow will correct all defects or prevent third party disruptions or unauthorized third party access. In the event of any inaccessibility of the BalmFlow Services, BalmFlow’s sole liability and obligation will as described in Exhibit A, which is hereby incorporated by reference. BalmFlow warranties will not apply if there has been misuse, modification, damage not caused by BalmFlow, failure to comply with instructions provided by BalmFlow, or if otherwise stated in in Exhibit A. 
Non-BalmFlow services are sold under the Agreement as-is, without warranties of any kind. Third parties may provide their own warranties to Client.

<BR/><B>8. LIMITATION OF LIABILITY</B><BR/>

BalmFlow’S ENTIRE LIABILITY FOR ALL CLAIMS RELATED TO THE AGREEMENT WILL NOT EXCEED THE AMOUNT OF ANY ACTUAL DIRECT DAMAGES INCURRED BY CLIENT, 
UP TO THE NET REVENUES ACTUALLY RECEIVED BY BalmFlow IN THE PRIOR 12 MONTHS WITH RESPECT TO THE SERVICES THAT ARE THE SUBJECT OF THE CLAIM, 
REGARDLESS OF THE BASIS OF THE CLAIM. BalmFlow WILL NOT BE LIABLE FOR SPECIAL, INCIDENTAL, EXEMPLARY, INDIRECT, OR ECONOMIC CONSEQUENTIAL DAMAGES, 
OR LOST PROFITS, BUSINESS, VALUE, REVENUE, GOODWILL, OR ANTICIPATED SAVINGS. 
THESE LIMITATIONS APPLY COLLECTIVELY TO BalmFlow, ITS AFFILIATES, CONTRACTORS AND END USERS. 
NOTWITHSTANDING THE FOREGOING, THE ABOVE LIMITATIONS ON LIABILITY SHALL NOT APPLY TO: 
(A) A BREACH OF SECTION 2(C) OR A BREACH OF SECTION 6, OR (B) A CLAIM FOR INDEMNIFICATION UNDER SECTION 9.

<BR/><B>9. INDEMNIFICATION</B><BR/>
Client agrees to indemnify, defend and hold harmless BalmFlow, its partners, agents, officers, directors and employees, from and against any loss, cost, expense, claim, injury or damage (including, without limitation, reasonable attorneys’ fees and expenses) (collectively, “Losses”) incurred due to third party claims arising from any breach by Client of any representation, warranty, or provision in this Agreement. BalmFlow shall indemnify, defend and hold Client harmless from and against any Losses incurred due to third party claims arising from any breach by BalmFlow of any representation, warranty, or provision contained in this Agreement.

<BR/><B>10. RELATIONSHIP OF PARTIES</B><BR/>
Neither this Agreement, the relationship created between the parties hereto pursuant to this Agreement, nor any course of dealing between the parties hereto is intended to create, or shall create, an employment relationship, a joint venture, partnership or any similar relationship. Each party is solely responsible for the payroll taxes, workman’s compensation insurance, and any other benefits owed to their own employees.

<BR/><B>11. PUBLICITY</B><BR/>
Neither party will issue any press releases or make any other public disclosures regarding this Agreement or its terms or the nature of the parties’ relationship without the other party’s prior written consent. Notwithstanding the foregoing, BalmFlow may list Client as a customer on its website and in marketing materials.

<BR/><B>12. ASSIGNMENT</B><BR/>
This Agreement and the rights hereunder are not transferable or assignable without prior written consent of the non-assigning party; provided, however, that this Agreement may be assigned by a party (a) to a person or entity who acquires substantially all of such party’s assets, stock or business by sale, merger or otherwise and (b) to an affiliate of such party.

<BR/><B>13. COMPLIANCE WITH LAWS</B><BR/>
Each party shall comply, at its own expense, with all statutes, regulations, rules, ordinances, and orders of any governmental body, department or agency that apply to or result from its obligations under this Agreement. If Client receives any notice or becomes aware of any violation of any law, statute, rule, regulation or ordinance with respect to the White-Labeled Services hereof, 
Client shall promptly notify BalmFlow of such notice or violation.

<BR/><B>14. GENERAL TERMS</B><BR/>
a. This Agreement (and any Exhibits hereto) constitutes the entire agreement between the parties with respect to the subject matter hereof, and may not be modified without the prior written consent of both parties. <br/>
<!--b. This Agreement will be governed and interpreted in accordance with the laws of the State of Massachusetts without reference to conflicts of laws principles.-->
c. BalmFlow will not be liable for any delay or failure to perform any of its obligations set forth in this Agreement due to causes beyond its reasonable control.<Br/>
d. No failure of either party to enforce any of its rights under this Agreement will act as a waiver of such rights.<br/>
e. Neither party will bring a legal action arising out of or related to the Agreement more than one year after the cause of action arose.<br/>
f. If one or more provisions of this Agreement are held to be unenforceable under applicable law, <br/>
then such provision(s) shall be excluded from this Agreement, and the balance of the Agreement shall be enforceable in accordance with its terms.
g. Any notice, demand or request required or permitted to be given under this Agreement shall be in writing and shall be deemed sufficient when sent by email to legal@balmflow.com. <br/>
Notice will be effective on receipt.<br/>
h. Headings and captions are for convenience only and are not to be used in the interpretation of the Agreement.

<BR/>
<BR/>
<B>SERVICE LEVEL TERMS</B><BR/>
<BR/><B>1. Definitions</B>
“Trading Service Downtime” means the number of minutes that BalmFlow Brokers couldn't execute trades for a Supported trade call advisories, but does not include any downtime otherwise excluded under section 4 below.
“Force Majeure Events” means any downtime minutes that are the result of events or conditions beyond BalmFlow’s reasonable control. 
Such events might include but are not limited to any acts of common enemy, the elements, earthquakes, floods, fires, epidemics, and inability to secure products or services from other persons or entities.
<BR/><B>2. Monitoring</B><BR/>
All Trading activities by BalmFlow 24 hours a day, 7 days per week. BalmFlow will inform Clients of all scheduled maintenance which could reasonably be expected to cause significant degradation in profitable trading activities or subject the Brokerage servers to downtime at least seven (7) days prior to the planned maintenance.
<Br/><B>3. 100% Uptime</B><BR/>
In the event that brokerage servers are not continuously available for trade execution (100% up time) as measured on a monthly basis, 
Client becomes eligible for a full refund if they so chose to recall the contributions set forth for The Foundation Project as set forth below. <br/>
Client shall be entitled to an extension of the Unbound period that would ordinarily be payable plus a credit for any incurred Penalties, if applicable, incurred as a result of such / extended trading server downtimes beyond the stated duration of Three (3) months .

<BR/><B>4. Exclusions</B><BR/>
Notwithstanding anything to the contrary herein, 
Client shall not be entitled to any credits hereunder if the trading servers or issues of any kind are caused by:<br/>
(i) acts or omissions of Client, <Br/>
(ii) scheduled BalmFlow network maintenance, <br/>
(iii) acts by a hacker or other malicious actor, <Br/>
(iv) Force Majeure events.<Br/>

<B>5. Required Notification & Timing of Credits</B><BR/>
No credits shall accrue under this Agreement until BalmFlow has actual notice of, or Client delivers to BalmFlow written notice of, the Trading Servers Downtime. 
Within thirty (30) days following the reporting on any of our trading servers downtime which results in Client being entitled to credits, 
BalmFlow shall deliver to Client detailed reporting specifying the approximate duration of the applicable failure and certifying to the best of BalmFlow’s knowledge the total amount of credits to which Client is entitled. In no event shall the total of any credits established under this Agreement for any month exceed the Net Revenue retained by BalmFlow during the applicable month. Credits will not carry over to future months. The credits provided shall be the sole remedies to Client in the event of the Staking Node Downtime.

BalmFlow LLC
  </p>
</div>  
</div>  
  </main>


@endsection