@extends('layouts.admin_app')
@section('content')

{{-- including the topbar --}}
@include('layouts.admin_topbar')



<div class="row">
			
			<!--navigation row-->
			
		 <div class="col-11">
              <div class="card mb-3 btn-reveal-trigger">

<br/>
  <div class="container"> @if (session('message'))   
    <div class="alert alert-success">  {{ session('message') }}</div>@endif</div>
         
			  
                <div class="card-header position-relative min-vh-25 mb-8">
                  <h6>Site-Wide Settings and Configuration</h6>
				<p><ul>
				<li><small style="font-size:10px">Assets and Investments data capture: These fields are updated on a daily basis for a total overview of the funds generated by the system on a daily basis</small></li>
				</ul>
            </p>
					
            {!! Form::open(['route' => 'update_settings', 'method'=>'POST'], ['class' => 'form']) !!}
            
            @csrf
            @method('PUT')
                       
            @foreach($config as $x)
            <div class="row">     
            <label class="label small">{{ ucfirst($x->key_option) }}</label>
           <div class="col-12">   
            <input type="text" class="form-control input-md bordered" name="{{ $x->id }}" value="{{$x->key_value}}"/></div>
            </div>

            @endforeach

            <div class="form-group bump-20"><button class="btn btn-danger" name="save_btn" id="saveConfig">Save Settings</button>
</div>

            {!! Form::close() !!}
					
                </div>
              </div>
            </div>

       </div>

@endsection